### ISSUE TITLE
How to keep in sync tracking from server side to client side when no email is provided?

### ISSUE THREAD

**Issue by hackhat** [Woopra/node-woopra#7]

**Comment by philosoralphter** [comment]
In order to keep un identified user actions on the correct profile between the client and server events, you must pass a cookie or any consistent value from the client to the server and then send it in the "cookie" parameter in th base of the request body. This could be your own cookie or ideally, the woopra cookie, available from our JavaScript SDK via `window.woopra.cookie` in the browser.
